version: '3'
services:     

  postgres:
    image: postgres:9.6
    container_name: "postgres"
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
    restart: always # every time start-up will restart